;----------------------------------------------------------------------------
; @(#)$CDS: assura version av3.1:Production:dfII5.0.0 07/29/2003 04:40 (source) $
;----------------------------------------------------------------------------


;----------------------------------------------------------------------------
; Assura 3.1 Template Version 1
;----------------------------------------------------------------------------

vuiRcxSetupFormOptions = '(
	((?vuiRCXFlowTab)
		(vuiOutputFormatSpectreButton      t)
		(vuiRCXDefaultOutputFormatType      "Spectre")
		(vuiOutputFormatDspfButton      t)
		(vuiOutputFormatSpefButton      t)
		(vuiOutputFormatSpiceButton      t)
		(vuiOutputFormatExtractedViewButton      t)
	)
	((?vuiRCXExtractionTab)
		(vuiRCXFCAN      t)
		(vuiRCXRLC      t)
		(vuiRCXFSFCAN      nil)
		(vuiRCXEnableRCXFS      t)
		(vuiRCXCOnly      t)
		(vuiRCXRLCK      t)
		(vuiRCXFSEN      nil)
		(vuiRCXEHrcx      t)
		(vuiRCXROnly      t)
		(vuiRCXRCOnly      t)
		(vuiRCXSP      t)
		(vuiRCXFSSP      nil)
		(vuiRCXEN      t)
		(vuiRCXExtractDefault      "R Only")
		(vuiRCXSNP      t)
		(vuiRCXFCSN      t)
		(vuiRCXFSSN      nil)
	)
	((?vuiRCXFilteringTab)
		(vuiRCXmergeParallelRReadOnly      nil)
		(vuiRCXFilterSizeReadOnly      nil)
		(vuiRCXexcludeSelfCapsReadOnly      nil)
		(vuiRCXmergeParallelR      nil)
		(vuiRCXFilterSize      "2.0")
		(vuiRCXminCReadOnly      nil)
		(vuiRCXexcludeFloatingNets      nil)
		(vuiRCXreduceRC      nil)
		(vuiRCXDanglingRReadOnly      nil)
		(vuiRCXMaxNoofSignals      "1000")
		(vuiRCXMaxClockReadOnly      nil)
		(vuiRCXmFactorReadOnly      nil)
		(vuiRCXexcludeFloatingNetsReadOnly      nil)
		(vuiRCXminR      "0.001")
		(vuiRCXminRReadOnly      nil)
		(vuiRCXexcludeFloatLimitReadOnly      nil)
		(vuiRCXRegionLimitReadOnly      nil)
		(vuiRCXMaxNoofSignalsReadOnly      nil)
		(vuiRCXMaxClock      "infinite")
		(vuiRCXDanglingR      nil)
		(vuiRCXexcludeFloatLimit      "2000000")
		(vuiRCXminC      "0.01")
		(vuiRCXRegionLimit      "200")
		(vuiRCXreduceRCReadOnly      nil)
		(vuiRCXexcludeSelfCaps      nil)
		(vuiRCXmFactor      "infinite")
	)
	((?vuiRCXNetlistingTab)
		(vuiRCXIgnoreNets      "")
		(vuiRCXXy_M      nil)
		(vuiRCXViaEffectOff      nil)
		(vuiRCXParasiticResWidth      nil)
		(vuiRCXSubNodeChar      "#")
		(vuiRCXParasiticCapModels      "Include Model")
		(vuiRCXXy_Q      nil)
		(vuiRCXImportGlobals      nil)
		(vuiRCXXy_R      nil)
		(vuiRCXOutputNetNameSpace      "Schematic")
		(vuiRCXXy_r      nil)
		(vuiRCXVirtualMetalFill      "Coeff")
		(vuiRCXResModels      "Do Not Include")
		(vuiRCXCapModels      "Do Not Include")
		(vuiRCXIgnoreLayer      "")
		(vuiRCXParasiticResModels      "Include As Comment")
		(vuiRCXAddExplicitVias      nil)
		(vuiRCXHierarchyDelimiter      "/")
		(vuiRCXXy_C      nil)
		(vuiRCXXy_D      nil)
		(vuiRCXXy_c      nil)
	)
	((?vuiRCXRunDetailsTab)
		(vuiRCXMultiMachineButton      t)
		(vuiRCXLSFButton      t)
	)

)
