
; Sample runset for 90 nm
; technology
; gpdk090 library CDF generated by GTE Version: v3.0USR4alpha  Build: 200506062105 (6892) on Jun 7, 2005

; parameter file: /home/johnag/work/srv2005/gpdk/gpdk009/SRC/gte/parameter.file
; CHECK_DENSITY false
; SUGGESTED_CHECK false

LIBRARY="gpdk090"

let((libId cdfId)
    unless(libId=ddGetObj(LIBRARY)
        error("Could not get library %s." LIBRARY)
    )
    when(cdfId=cdfGetBaseLibCDF(libId)
        cdfDeleteCDF(cdfId)
    )
    cdfId=cdfCreateBaseLibCDF(libId)


    cdfId->simInfo = list(nil)

    cdfId->formInitProc           = ""
    cdfId->doneProc               = ""
    cdfId->buttonFieldWidth       = 340
    cdfId->fieldHeight            = 35
    cdfId->fieldWidth             = 350
    cdfId->promptWidth            = 175
    cdfId->paramEvaluate          = "t nil nil nil nil"
    cdfId->paramSimType           = "DC"
    cdfId->paramDisplayMode       = "parameter"
    cdfId->netNameType            = "schematic"
    cdfId->termSimType            = "DC"
    cdfId->termDisplayMode        = "none"
    cdfId->instNameType           = "schematic"
    cdfId->instDisplayMode        = "instName"
    cdfSaveCDF(cdfId)
)
